[2025-04-15T19:35:18.649+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T19:35:19.451+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_quality.check_customer_key_duplicate scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-15T19:35:19.504+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_quality.check_customer_key_duplicate scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-15T19:35:19.506+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-15T19:35:19.583+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): check_customer_key_duplicate> on 2025-04-13 00:00:00+00:00
[2025-04-15T19:35:20.156+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=11295) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-15T19:35:20.271+0000] {standard_task_runner.py:72} INFO - Started process 11313 to run task
[2025-04-15T19:35:20.364+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_data_quality', 'check_customer_key_duplicate', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_quality.py', '--cfg-path', '/tmp/tmpn95l3qdp']
[2025-04-15T19:35:20.391+0000] {standard_task_runner.py:105} INFO - Job 152: Subtask check_customer_key_duplicate
[2025-04-15T19:35:22.395+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_data_quality.check_customer_key_duplicate scheduled__2025-04-13T00:00:00+00:00 [running]> on host 697c9a4320f6
[2025-04-15T19:35:23.526+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='laurenziusjulioanreaja@mail.ugm.ac.id,selvianisacahyamukti@mail.ugm.ac.id,yudypratamafanggidae@mail.ugm.ac.id' AIRFLOW_CTX_DAG_OWNER='julio' AIRFLOW_CTX_DAG_ID='dag_data_quality' AIRFLOW_CTX_TASK_ID='check_customer_key_duplicate' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-15T19:35:23.542+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-15T19:35:23.545+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-15T19:35:23.547+0000] {logging_mixin.py:190} INFO - Current task name:check_customer_key_duplicate state:running start_date:2025-04-15 19:35:19.452865+00:00
[2025-04-15T19:35:23.549+0000] {logging_mixin.py:190} INFO - Dag name:dag_data_quality and current dag run status:running
[2025-04-15T19:35:23.552+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T19:35:24.968+0000] {python.py:240} INFO - Done. Returned value was: âœ… customer_key OK, tidak ada duplikat
[2025-04-15T19:35:25.110+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-15T19:35:25.115+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_data_quality, task_id=check_customer_key_duplicate, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250415T193519, end_date=20250415T193525
[2025-04-15T19:35:25.259+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-15T19:35:25.261+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-15T19:35:25.262+0000] {logging_mixin.py:190} INFO - Dag name:dag_data_quality queued_at:2025-04-14 02:50:50.652583+00:00
[2025-04-15T19:35:25.263+0000] {logging_mixin.py:190} INFO - Task hostname:697c9a4320f6 operator:_PythonDecoratedOperator
[2025-04-15T19:35:25.311+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-15T19:35:25.355+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-15T19:35:25.384+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-04-15T19:35:44.308+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T19:35:44.343+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: dag_data_quality.check_customer_key_duplicate scheduled__2025-04-13T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-04-15T19:35:44.370+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
