[2025-04-20T10:19:30.039+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-20T10:19:30.067+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migrate_duckdb_to_sqlite.migrate_all_tables manual__2025-04-20T10:19:26.462380+00:00 [queued]>
[2025-04-20T10:19:30.081+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migrate_duckdb_to_sqlite.migrate_all_tables manual__2025-04-20T10:19:26.462380+00:00 [queued]>
[2025-04-20T10:19:30.082+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-20T10:19:30.104+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): migrate_all_tables> on 2025-04-20 10:19:26.462380+00:00
[2025-04-20T10:19:30.125+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=140) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-20T10:19:30.125+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'migrate_duckdb_to_sqlite', 'migrate_all_tables', 'manual__2025-04-20T10:19:26.462380+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_migration_sqlite.py', '--cfg-path', '/tmp/tmpsqakxt24']
[2025-04-20T10:19:30.127+0000] {standard_task_runner.py:72} INFO - Started process 142 to run task
[2025-04-20T10:19:30.128+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask migrate_all_tables
[2025-04-20T10:19:30.213+0000] {task_command.py:467} INFO - Running <TaskInstance: migrate_duckdb_to_sqlite.migrate_all_tables manual__2025-04-20T10:19:26.462380+00:00 [running]> on host 1729986aabcb
[2025-04-20T10:19:30.347+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='migrate_duckdb_to_sqlite' AIRFLOW_CTX_TASK_ID='migrate_all_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T10:19:26.462380+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T10:19:26.462380+00:00'
[2025-04-20T10:19:30.350+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-20T10:19:30.351+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-20T10:19:30.352+0000] {logging_mixin.py:190} INFO - Current task name:migrate_all_tables state:running start_date:2025-04-20 10:19:30.068523+00:00
[2025-04-20T10:19:30.352+0000] {logging_mixin.py:190} INFO - Dag name:migrate_duckdb_to_sqlite and current dag run status:running
[2025-04-20T10:19:30.353+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-20T10:19:30.399+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_migration_sqlite.py", line 16, in migrate_duckdb_to_sqlite
    con_sqlite = sqlite3.connect(SQLITE_PATH)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
[2025-04-20T10:19:30.424+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-20T10:19:30.425+0000] {logging_mixin.py:190} INFO - Task start:2025-04-20 10:19:30.068523+00:00 end:2025-04-20 10:19:30.423140+00:00 duration:0.354617
[2025-04-20T10:19:30.426+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): migrate_all_tables> dag:<DAG: migrate_duckdb_to_sqlite> dagrun:<DagRun migrate_duckdb_to_sqlite @ 2025-04-20 10:19:26.462380+00:00: manual__2025-04-20T10:19:26.462380+00:00, state:running, queued_at: 2025-04-20 10:19:26.491537+00:00. externally triggered: True>
[2025-04-20T10:19:30.427+0000] {logging_mixin.py:190} INFO - Failure caused by unable to open database file
[2025-04-20T10:19:30.427+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=migrate_duckdb_to_sqlite, task_id=migrate_all_tables, run_id=manual__2025-04-20T10:19:26.462380+00:00, execution_date=20250420T101926, start_date=20250420T101930, end_date=20250420T101930
[2025-04-20T10:19:30.461+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-20T10:19:30.462+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task migrate_all_tables (unable to open database file; 142)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_migration_sqlite.py", line 16, in migrate_duckdb_to_sqlite
    con_sqlite = sqlite3.connect(SQLITE_PATH)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
[2025-04-20T10:19:30.505+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-20T10:19:30.529+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-20T10:19:30.532+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
