[2025-04-01T02:30:55.389+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T02:30:55.653+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_duckdb_example.query_duckdb manual__2025-04-01T02:30:39.101770+00:00 [queued]>
[2025-04-01T02:30:55.665+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_duckdb_example.query_duckdb manual__2025-04-01T02:30:39.101770+00:00 [queued]>
[2025-04-01T02:30:55.666+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-01T02:30:55.683+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): query_duckdb> on 2025-04-01 02:30:39.101770+00:00
[2025-04-01T02:30:55.694+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-01T02:30:55.696+0000] {standard_task_runner.py:72} INFO - Started process 283 to run task
[2025-04-01T02:30:55.697+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_duckdb_example', 'query_duckdb', 'manual__2025-04-01T02:30:39.101770+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/etl_duckdb.py', '--cfg-path', '/tmp/tmpkm8ej5vh']
[2025-04-01T02:30:55.698+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask query_duckdb
[2025-04-01T02:30:55.750+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_duckdb_example.query_duckdb manual__2025-04-01T02:30:39.101770+00:00 [running]> on host 652bd9ea4c03
[2025-04-01T02:30:55.884+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_duckdb_example' AIRFLOW_CTX_TASK_ID='query_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T02:30:39.101770+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T02:30:39.101770+00:00'
[2025-04-01T02:30:55.887+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-01T02:30:55.888+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-01T02:30:55.889+0000] {logging_mixin.py:190} INFO - Current task name:query_duckdb state:running start_date:2025-04-01 02:30:55.655578+00:00
[2025-04-01T02:30:55.890+0000] {logging_mixin.py:190} INFO - Dag name:etl_duckdb_example and current dag run status:running
[2025-04-01T02:30:55.891+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T02:30:56.253+0000] {logging_mixin.py:190} INFO - Gagal menjalankan query ke DuckDB: Catalog Error: Table with name dim_customer does not exist!
Did you mean "duckdb_types"?

LINE 1: SELECT * FROM dim_customer LIMIT 5
                      ^
[2025-04-01T02:30:56.262+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-01T02:30:56.282+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T02:30:56.283+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_duckdb_example, task_id=query_duckdb, run_id=manual__2025-04-01T02:30:39.101770+00:00, execution_date=20250401T023039, start_date=20250401T023055, end_date=20250401T023056
[2025-04-01T02:30:56.319+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-01T02:30:56.320+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-01T02:30:56.321+0000] {logging_mixin.py:190} INFO - Dag name:etl_duckdb_example queued_at:2025-04-01 02:30:39.361251+00:00
[2025-04-01T02:30:56.321+0000] {logging_mixin.py:190} INFO - Task hostname:652bd9ea4c03 operator:PythonOperator
[2025-04-01T02:30:56.355+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T02:30:56.380+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-01T02:30:56.383+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
