[2025-04-01T16:49:34.664+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T16:49:34.685+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_duckdb.query_duckdb manual__2025-04-01T16:49:14.879219+00:00 [queued]>
[2025-04-01T16:49:34.873+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_duckdb.query_duckdb manual__2025-04-01T16:49:14.879219+00:00 [queued]>
[2025-04-01T16:49:34.874+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-01T16:49:34.892+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): query_duckdb> on 2025-04-01 16:49:14.879219+00:00
[2025-04-01T16:49:34.910+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1931) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-01T16:49:34.911+0000] {standard_task_runner.py:72} INFO - Started process 1940 to run task
[2025-04-01T16:49:34.911+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_duckdb', 'query_duckdb', 'manual__2025-04-01T16:49:14.879219+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_duckdb.py', '--cfg-path', '/tmp/tmpwjqy2bcm']
[2025-04-01T16:49:34.913+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask query_duckdb
[2025-04-01T16:49:34.970+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_duckdb.query_duckdb manual__2025-04-01T16:49:14.879219+00:00 [running]> on host 1df6dff01eb9
[2025-04-01T16:49:35.087+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_duckdb' AIRFLOW_CTX_TASK_ID='query_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T16:49:14.879219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T16:49:14.879219+00:00'
[2025-04-01T16:49:35.089+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-01T16:49:35.089+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-01T16:49:35.090+0000] {logging_mixin.py:190} INFO - Current task name:query_duckdb state:running start_date:2025-04-01 16:49:34.686396+00:00
[2025-04-01T16:49:35.090+0000] {logging_mixin.py:190} INFO - Dag name:etl_duckdb and current dag run status:running
[2025-04-01T16:49:35.090+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T16:49:35.329+0000] {logging_mixin.py:190} INFO - Gagal menjalankan query ke DuckDB: Catalog Error: Table with name dim_time does not exist!
Did you mean "duckdb_types or pg_attribute"?

LINE 1: SELECT * FROM dim_time LIMIT 5
                      ^
[2025-04-01T16:49:35.338+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-01T16:49:35.361+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T16:49:35.362+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_duckdb, task_id=query_duckdb, run_id=manual__2025-04-01T16:49:14.879219+00:00, execution_date=20250401T164914, start_date=20250401T164934, end_date=20250401T164935
[2025-04-01T16:49:35.413+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-01T16:49:35.414+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-01T16:49:35.415+0000] {logging_mixin.py:190} INFO - Dag name:etl_duckdb queued_at:2025-04-01 16:49:15.096243+00:00
[2025-04-01T16:49:35.416+0000] {logging_mixin.py:190} INFO - Task hostname:1df6dff01eb9 operator:PythonOperator
[2025-04-01T16:49:35.449+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T16:49:35.476+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-01T16:49:35.481+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
